version: 2
registries:
  public:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  registries: 
    - public
  target-branch: "development"
  open-pull-requests-limit: 10