name: _Template Build
on:
  workflow_call:
    inputs:
      project:
        description: 'The *csproj project path passed from the caller workflow'
        required: true
        type: string
jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3.0.2

      - name: Cache dependencies
        uses: actions/cache@v3.0.11
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget  

      - name: Install dependencies
        working-directory: ${{ inputs.project }}
        run: dotnet restore

      - name: Build
        working-directory: ${{ inputs.project }}
        run: dotnet build --configuration Release --no-restore