name: Banner - Command
run-name: Banner Command Workflow

on:
  push:
    paths:
      - src/Services/Banner/Command/**.cs
      - src/Services/Banner/Command/**.csproj
      - test/BannerTest/**.cs
      - test/BannerTest/**.csproj
      - Directory.Build.props
      - .github/workflows/banner-command.yaml

jobs:
  call-workflow:
    uses: ./.github/workflows/_workflow.yaml
    with:
      path: src/Services/Banner/Command
      project: WorkerService
      test: test/BannerTest 